version: '3.8'

services:
  marvin_memory:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    environment:
      - QDRANT_HOST=172.236.30.19  # Using the server's IP to connect to existing Qdrant
      - QDRANT_PORT=6333
    restart: unless-stopped

volumes:
  qdrant_data:

networks:
  marvin_net:
    driver: bridge 