version: '3.8'

services:
  marvin_memory:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    environment:
      - QDRANT_HOST=qdrant  # Using the container name of the existing Qdrant instance
      - QDRANT_PORT=6333
    restart: unless-stopped
    network_mode: "container:qdrant"  # Connect directly to the Qdrant container's network

volumes:
  qdrant_data:

networks:
  marvin_net:
    driver: bridge 