version: '3.8'

services:
  marvin_memory:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant.marvn.club  # Updated to point to the correct Qdrant server
      - QDRANT_PORT=6333
    restart: unless-stopped
    network_mode: bridge  # Use default bridge network
    extra_hosts:
      - "qdrant:172.236.30.19"  # Map the container name to the host IP

volumes:
  qdrant_data:
