version: '3.8'

services:
  marvin_memory:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    environment:
      - QDRANT_HOST=qdrant  # Using the container name of the existing Qdrant instance
      - QDRANT_PORT=6333
    restart: unless-stopped
    network_mode: bridge  # Use default bridge network
    extra_hosts:
      - "qdrant:172.236.30.19"  # Map the container name to the host IP

volumes:
  qdrant_data:

networks:
  marvin_net:
    driver: bridge 